# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assignment_num',
        ),
    ]
