# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign5', '0002_remove_submission_assignment_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assignment_num',
            field=models.IntegerField(default=0),
        ),
    ]
