# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign5', '0005_auto_20171008_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=10)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_num', models.IntegerField(default=0)),
                ('pomlocation', models.CharField(max_length=500)),
                ('eid', models.CharField(max_length=10)),
                ('mvnstarted', models.BooleanField()),
                ('mvnended', models.BooleanField()),
                ('hadoopstarted', models.BooleanField()),
                ('hadoopended', models.BooleanField()),
                ('foundoutput', models.BooleanField()),
                ('numberoflines', models.IntegerField()),
                ('numberofkeymatches', models.IntegerField()),
                ('events_sorted', models.BooleanField()),
                ('features_sorted', models.BooleanField()),
                ('completed', models.BooleanField()),
                ('errors', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
