# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign5', '0006_subresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subresults',
            name='foundoutput',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subresults',
            name='hadoopended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subresults',
            name='hadoopstarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subresults',
            name='mvnended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subresults',
            name='mvnstarted',
            field=models.BooleanField(default=False),
        ),
    ]
