# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign5', '0007_auto_20171008_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subresults',
            name='numberofkeymatches',
            field=models.IntegerField(default=-999),
        ),
        migrations.AlterField(
            model_name='subresults',
            name='numberoflines',
            field=models.IntegerField(default=-999),
        ),
    ]
